# Generated by Azure Infrastructure Prompt Kit
resource "azurerm_static_web_app" "main" {
  name                = "stapp-${var.project_name}-${var.environment}"
  location            = var.location
  resource_group_name = var.resource_group_name
  sku_size            = var.sku_name
  sku_tier            = var.sku_name
  tags                = var.tags
}
