# Generated by Azure Infrastructure Prompt Kit
output "static_web_app_id" {
  description = "The ID of the Static Web App"
  value       = azurerm_static_web_app.main.id
}

output "default_hostname" {
  description = "The default hostname of the Static Web App"
  value       = azurerm_static_web_app.main.default_host_name
}
