# Generated by Azure Infrastructure Prompt Kit
output "resource_group_name" {
  description = "The name of the resource group"
  value       = azurerm_resource_group.main.name
}

output "key_vault_uri" {
  description = "The URI of the Key Vault"
  value       = module.security.key_vault_uri
}

output "static_web_app_hostname" {
  description = "The default hostname of the Static Web App"
  value       = module.compute_web_frontend.default_hostname
}

output "container_app_fqdn" {
  description = "The FQDN of the Container App"
  value       = module.compute_api_backend.container_app_fqdn
}

output "sql_server_fqdn" {
  description = "The FQDN of the SQL Server"
  value       = module.data_customer_database.sql_server_fqdn
  sensitive   = true
}
