# Generated by Azure Infrastructure Prompt Kit
variable "environment" {
  description = "The deployment environment"
  type        = string

  validation {
    condition     = contains(["dev", "staging", "prod"], var.environment)
    error_message = "Environment must be dev, staging, or prod."
  }
}

variable "location" {
  description = "The Azure region for all resources"
  type        = string
  default     = "westeurope"
}

variable "project_name" {
  description = "The project name used for resource naming"
  type        = string
  default     = "customerportal"
}

variable "sql_sku_name" {
  description = "The SKU name for Azure SQL Database"
  type        = string
  default     = "GP_Gen5_2"
}

variable "container_app_min_replicas" {
  description = "Minimum number of container app replicas"
  type        = number
  default     = 0
}

variable "container_app_max_replicas" {
  description = "Maximum number of container app replicas"
  type        = number
  default     = 10
}

variable "static_web_app_sku" {
  description = "The SKU for Static Web Apps"
  type        = string
  default     = "Standard"
}
