# Generated by Azure Infrastructure Prompt Kit
resource "random_string" "sql_suffix" {
  length  = 6
  special = false
  upper   = false
}

resource "random_password" "sql_admin" {
  length  = 32
  special = true
}

resource "azurerm_mssql_server" "main" {
  name                          = "sql-${var.project_name}-${var.environment}-${random_string.sql_suffix.result}"
  location                      = var.location
  resource_group_name           = var.resource_group_name
  version                       = "12.0"
  administrator_login           = "sqladmin"
  administrator_login_password  = random_password.sql_admin.result
  minimum_tls_version           = "1.2"
  public_network_access_enabled = false
  tags                          = var.tags

  identity {
    type         = "UserAssigned"
    identity_ids = [var.managed_identity_id]
  }
}

resource "azurerm_mssql_database" "main" {
  name                        = "sqldb-${var.project_name}-${var.environment}"
  server_id                   = azurerm_mssql_server.main.id
  collation                   = "SQL_Latin1_General_CP1_CI_AS"
  sku_name                    = var.sku_name
  zone_redundant              = var.environment == "prod"
  storage_account_type        = var.environment == "prod" ? "Geo" : "Local"
  tags                        = var.tags
}

resource "azurerm_private_endpoint" "sql" {
  name                = "pe-sql-${var.project_name}-${var.environment}"
  location            = var.location
  resource_group_name = var.resource_group_name
  subnet_id           = var.subnet_id
  tags                = var.tags

  private_service_connection {
    name                           = "sql-connection"
    private_connection_resource_id = azurerm_mssql_server.main.id
    subresource_names              = ["sqlServer"]
    is_manual_connection           = false
  }
}

resource "azurerm_key_vault_secret" "sql_connection_string" {
  name         = "sql-connection-string"
  value        = "Server=tcp:${azurerm_mssql_server.main.fully_qualified_domain_name},1433;Database=${azurerm_mssql_database.main.name};Authentication=Active Directory Default;"
  key_vault_id = var.key_vault_id
}
