# Generated by Azure Infrastructure Prompt Kit
output "sql_server_fqdn" {
  description = "The FQDN of the SQL Server"
  value       = azurerm_mssql_server.main.fully_qualified_domain_name
  sensitive   = true
}

output "database_name" {
  description = "The name of the SQL Database"
  value       = azurerm_mssql_database.main.name
}
