# Generated by Azure Infrastructure Prompt Kit
variable "resource_group_name" {
  description = "The name of the resource group"
  type        = string
}

variable "location" {
  description = "The Azure region"
  type        = string
}

variable "project_name" {
  description = "The project name"
  type        = string
}

variable "environment" {
  description = "The deployment environment"
  type        = string
}

variable "subnet_id" {
  description = "The subnet ID for private endpoint"
  type        = string
}

variable "key_vault_id" {
  description = "The Key Vault ID for storing connection strings"
  type        = string
}

variable "managed_identity_id" {
  description = "The managed identity resource ID"
  type        = string
}

variable "sku_name" {
  description = "The SKU name for Azure SQL Database"
  type        = string
  default     = "GP_Gen5_2"
}

variable "tags" {
  description = "Tags to apply to all resources"
  type        = map(string)
}
