# Generated by Azure Infrastructure Prompt Kit
# Uncomment and configure for remote state storage:
#
# terraform {
#   backend "azurerm" {
#     resource_group_name  = "rg-terraform-state"
#     storage_account_name = "stterraformstate"
#     container_name       = "tfstate"
#     key                  = "customerportal.terraform.tfstate"
#   }
# }
