# Generated by Azure Infrastructure Prompt Kit
locals {
  tags = {
    environment = var.environment
    project     = var.project_name
    managed_by  = "terraform"
  }
}

resource "azurerm_resource_group" "main" {
  name     = "rg-${var.project_name}-${var.environment}"
  location = var.location
  tags     = local.tags
}

module "networking" {
  source = "./modules/networking"

  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  project_name        = var.project_name
  environment         = var.environment
  tags                = local.tags
}

module "security" {
  source = "./modules/security"

  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  project_name        = var.project_name
  environment         = var.environment
  tags                = local.tags
}

module "monitoring" {
  source = "./modules/monitoring"

  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  project_name        = var.project_name
  environment         = var.environment
  tags                = local.tags
}

module "compute_web_frontend" {
  source = "./modules/compute-web-frontend"

  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  project_name        = var.project_name
  environment         = var.environment
  sku_name            = var.static_web_app_sku
  tags                = local.tags
}

module "compute_api_backend" {
  source = "./modules/compute-api-backend"

  resource_group_name              = azurerm_resource_group.main.name
  location                         = azurerm_resource_group.main.location
  project_name                     = var.project_name
  environment                      = var.environment
  subnet_id                        = module.networking.compute_subnet_id
  managed_identity_id              = module.security.managed_identity_id
  app_insights_connection_string   = module.monitoring.app_insights_connection_string
  min_replicas                     = var.container_app_min_replicas
  max_replicas                     = var.container_app_max_replicas
  tags                             = local.tags
}

module "data_customer_database" {
  source = "./modules/data-customer-database"

  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  project_name        = var.project_name
  environment         = var.environment
  subnet_id           = module.networking.data_subnet_id
  key_vault_id        = module.security.key_vault_id
  managed_identity_id = module.security.managed_identity_id
  sku_name            = var.sql_sku_name
  tags                = local.tags
}
