# Generated by Azure Infrastructure Prompt Kit
output "vnet_id" {
  description = "The ID of the virtual network"
  value       = azurerm_virtual_network.main.id
}

output "compute_subnet_id" {
  description = "The ID of the compute subnet"
  value       = azurerm_subnet.compute.id
}

output "data_subnet_id" {
  description = "The ID of the data subnet"
  value       = azurerm_subnet.data.id
}

output "integration_subnet_id" {
  description = "The ID of the integration subnet"
  value       = azurerm_subnet.integration.id
}
