# Generated by Azure Infrastructure Prompt Kit
output "container_app_fqdn" {
  description = "The FQDN of the Container App"
  value       = azurerm_container_app.api.ingress[0].fqdn
}

output "container_app_environment_id" {
  description = "The ID of the Container App Environment"
  value       = azurerm_container_app_environment.main.id
}
